services:
  app:
    image: app
    build:
      context: .
      dockerfile: Pingjata/Dockerfile
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_HOST=db
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_DATABASE=${POSTGRES_DB}
    networks:
      app:

  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      app:
      db:

networks:
  app:
  db: