name: "Build and publish"

on:
  release:
    types:
      - released

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install dependencies
        run: dotnet restore *.sln

      - name: Build application
        run: dotnet build *.sln